n=str(input('Digite um número:'))
print('Analisando o número {}:'.format(n))
print('Unidades: {}'.format(n[3]))
print('Dezenas: {}'.format(n[2]))
print('Centenas: {}'.format(n[1]))
print('Milhar: {}'.format(n[0]))